FROM debian:latest

RUN apt-get update && apt-get install -y curl software-properties-common
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

WORKDIR /opt/agentpanel

ENV PATH /opt/agentpanel/frontend/node_modules/.bin:$PATH

RUN mkdir /etc/voicespin-apps
COPY config.json /etc/voicespin-apps
COPY ./frontend/package.json /opt/agentpanel/frontend/
COPY ./backend/package.json /opt/agentpanel/backend/
RUN npm install --prefix backend
RUN npm install --prefix frontend
COPY . /opt/agentpanel

RUN ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
CMD npm run start:dev --prefix backend
