#!/bin/bash

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Running Linters:"

# Run tslint and get the output and return code
folders=( frontend backend )

for folder in "${folders[@]}"
do
    pushd $folder

    tslint=$(npm run lint)
    ret_code=$?

    # If it didn't pass, announce it failed and print the output
    if [ $ret_code != 0 ]; then
        printf "\n${RED}tslint failed:${NC}"
        echo "$tslint\n"
        pass=false
        exit 1
    else
        printf "${GREEN}$folder: tslint passed${NC}\n"
    fi
        popd
done
